%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: C:\Users\Olga\Trainig\HarmonicOscilator231106\ho_mu0.txt
%
% Auto-generated by MATLAB on 06-Nov-2023 13:39:46

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 6);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["VarName1", "times1", "countA", "countB", "countC", "countD"];
opts.VariableTypes = ["double", "double", "double", "string", "string", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["countB", "countC", "countD"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["countB", "countC", "countD"], "EmptyFieldRule", "auto");

% Import the data

tbl = readtable(file_to_load, opts);

%% Convert to output type
VarName1 = tbl.VarName1;
times1 = tbl.times1;
countA = tbl.countA;
countB = tbl.countB;
countC = tbl.countC;
countD = tbl.countD;

%% Clear temporary variables
clear opts tbl